kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: model-training-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lvms-vg1
