= Automation using Data Science Pipelines
:navtitle: Home

Welcome to this quick course on the _Automation using Data Science Pipelines_.
This course is the *fifth* in a series of *five* courses about Red Hat OpenShift AI:

1. https://redhatquickcourses.github.io/rhods-intro[Introduction to Red Hat OpenShift AI]
2. https://redhatquickcourses.github.io/rhods-admin[Red Hat OpenShift AI Administration]
3. https://redhatquickcourses.github.io/rhods-model[Creating Machine Learning Models with Red Hat OpenShift AI]
4. https://redhatquickcourses.github.io/rhods-deploy[Deploying Machine Learning Models with Red Hat OpenShift AI]
5. Automation using Data Science Pipelines (_This course_)

NOTE: After you have completed all the courses in the learning path, you can attempt the https://github.com/RedHatQuickCourses/rhods-qc-apps/tree/main/7.hands-on-lab["Workshop final hands-on Lab"] exercise, that tests your understanding of the concepts taught in all the courses.

== Authors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Noel O'Connor
* Jaime Ramirez Castillo
* Max Murakami
* Codrin Bucur
* Sameera Meduri
* Ravi Srinivasan

== Classroom Environment for Red Hat Associates

Continue using the https://demo.redhat.com/catalog?search=Red+Hat+OpenShift+Container+Platform+Workshop&item=babylon-catalog-prod%2Fopenshift-cnv.ocpmulti-wksp-cnv.prod[Red Hat OpenShift Container Platform Cluster] classroom that you provisioned in the _Red Hat OpenShift AI Administration_ course.

You are expected to complete the _Red Hat OpenShift AI Administration_ course, where you install and configure a basic RHOAI instance, and then continue with this course.

== Classroom Environment for Red Hat Partners

Red Hat partners should continue to use the Red Hat OpenShift AI cluster provisioned in the _Red Hat OpenShift AI Administration_ course, using the Red Hat Hybrid Cloud Console at https://console.redhat.com/openshift/overview.

You are expected to complete the _Red Hat OpenShift AI Administration_ course, where you install and configure a basic RHOAI instance, and then continue with this course.

== Prerequisites

* Basic knowledge of OpenShift (or Kubernetes) administration
* Building and deploying container images
* User and role administration
* Configuring cluster storage (PV, PVC)
* Experience with OpenShift is recommended, but not mandatory (in case students have to do troubleshooting)

== Objectives

The overall objectives of this course include:

* Describe Kubeflow and Elyra Pipelines
* Create Data Science Pipelines
* Run Data Science Pipelines
* Manage Data Science Pipelines
* Troubleshoot Data Science Pipelines
