= Automation using Data Science Pipelines
:navtitle: Home

Welcome to this quick course on the _Automation using Data Science Pipelines_.
This course is the *fifth* in a series of *five* courses about Red Hat OpenShift AI:

1. https://redhatquickcourses.github.io/rhods-intro[Introduction to Red Hat OpenShift AI]
2. https://redhatquickcourses.github.io/rhods-admin[Red Hat OpenShift AI Administration]
3. https://redhatquickcourses.github.io/rhods-model[Creating Machine Learning Models with Red Hat OpenShift AI]
4. https://redhatquickcourses.github.io/rhods-deploy[Deploying Machine Learning Models with Red Hat OpenShift AI]
5. Automation using Data Science Pipelines (_This course_)

NOTE: After you have completed all the courses in the learning path, you can attempt the https://github.com/RedHatQuickCourses/rhods-qc-apps/tree/main/7.hands-on-lab["Hit the RHODS"] exercise, that tests your understanding of the concepts taught in all the courses.

== Authors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Noel O'Connor
* Jaime Ramirez Castillo
* Max Murakami
* Codrin Bucur
* Sameera Meduri
* Ravi Srinivasan

== Classroom Environment

There are two options, based on whether you are taking this course standalone (just this course), or as part of the full 6 course learning path where you installed RHOAI on an OpenShift cluster in the second course in the learning path, _Red Hat OpenShift AI Administration_.

=== Option 1: Standalone (RHOAI Pre-installed on OpenShift)

You will use the https://demo.redhat.com/catalog?search=openshift+data+science&item=babylon-catalog-prod%2Fsandboxes-gpte.ocp4-workshop-rhods-base-aws.prod[Base RHODS on AWS] catalog item in the Red Hat Demo Platform (RHDP) to run the hands on exercises in this course.

This classroom has a pre-installed version of Red Hat OpenShift AI on OpenShift. 

=== Option 2: Five Course Learning Path

Continue using the https://demo.redhat.com/catalog?search=Red+Hat+OpenShift+Container+Platform+4.13+Workshop&item=babylon-catalog-prod%2Fopenshift-cnv.ocp413-wksp-cnv.prod[Red Hat OpenShift Container Platform 4.13 Workshop] catalog item from the _Red Hat OpenShift AI Administration_ course.

[TIP]
====
To prevent problems when allocating pipeline and workbench pods, make sure that your catalog item has been configured with `64Gi` as the worker memory size.
====

This classroom does *NOT* have RHOAI pre-installed. You are expected to complete the _Red Hat OpenShift AI Administration_ course, where you install and configure a basic RHOAI instance, and then continue with this course.

== Prerequisites

* Basic knowledge of OpenShift (or Kubernetes) administration
* Building and deploying container images
* User and role administration
* Configuring cluster storage (PV, PVC)
* Basic knowledge of using OpenShift Pipelines or Tekton for automating continuous integration and continuous deployment (CI/CD) pipelines
* Experience with OpenShift is recommended, but not mandatory (in case students have to do troubleshooting)

== Objectives

The overall objectives of this course include:

* Describe KubeFlow and Elyra pipelines
* Creating Data Science pipelines
* Running Data Science pipelines
* Manage Data Science pipelines
* Troubleshooting Data Science pipelines
