kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: offline-scoring-model-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
